# Generated from analysis/bg_implement.Rmd.
# Do not edit this file directly.

# ---- f-updates ----
# Calculate qF moments and the soft counts needed by update_pi().
# A p x M responsibility matrix is created for one factor k, summarized, and
# discarded before moving to the next factor; no p x K x M array is retained.
refresh_qF_moments <- function(C, f0, L_sum, pi, a) {
  p <- nrow(C)
  K <- ncol(C)
  M <- length(a)
  mean <- mean_log <- matrix(0, p, K)
  resp_sumj <- matrix(0, K, M)
  mixture_term <- 0
  log_pi <- log(pi)
  prior_constant <- a * log(a) - lgamma(a)

  for (k in seq_len(K)) {
    C_k <- C[, k]
    D_k <- f0 * L_sum[k]
    active <- which(pi[, k] > 0)
    if (!length(active)) {
      stop("Each column of pi must contain positive mass.")
    }

    # log_resp is only p x M for the current factor. Zero-weight components
    # stay at -Inf and receive exactly zero responsibility.
    log_resp <- matrix(-Inf, p, M)
    for (m in active) {
      shape <- C_k + a[m]
      rate <- D_k + a[m]
      log_resp[, m] <-
        log_pi[m, k] + prior_constant[m] +
        lgamma(shape) - shape * log(rate)
    }

    # Stable row-wise softmax without apply(), which avoids additional large
    # intermediate arrays.
    row_max <- log_resp[, active[1L]]
    if (length(active) > 1L) {
      for (m in active[-1L]) {
        row_max <- pmax(row_max, log_resp[, m])
      }
    }

    row_sum <- numeric(p)
    for (m in active) {
      log_resp[, m] <- exp(log_resp[, m] - row_max)
      row_sum <- row_sum + log_resp[, m]
    }

    mean_k <- mean_log_k <- numeric(p)
    for (m in active) {
      responsibility <- log_resp[, m] / row_sum
      shape <- C_k + a[m]
      rate <- D_k + a[m]
      mean_k <- mean_k + responsibility * shape / rate
      mean_log_k <- mean_log_k +
        responsibility * (digamma(shape) - log(rate))
      resp_sumj[k, m] <- sum(responsibility)
    }

    mean[, k] <- mean_k
    mean_log[, k] <- mean_log_k

    # Because qF is the coordinate-optimal distribution, log_normalizer is
    # its local objective including log(pi). Remove the expected Poisson
    # contribution C * E[log(F)] - D * E[F] to obtain the qF mixture term.
    mixture_term <- mixture_term + sum(
      row_max + log(row_sum) - C_k * mean_log_k + D_k * mean_k
    )
  }

  # Retain only the pi-independent portion. If update_pi() subsequently
  # changes pi, calculate_elbo() can add sum_jkm r_jkm * log(pi_mk) from the
  # small K x M matrix resp_sumj; the full responsibility tensor is unneeded.
  positive_pi <- pi > 0
  mixture_base <- mixture_term - sum(
    t(resp_sumj)[positive_pi] * log_pi[positive_pi]
  )

  list(
    mean = mean,
    mean_log = mean_log,
    resp_sumj = resp_sumj,
    mixture_base = mixture_base
  )
}

# Main qF update. C already exists as qZ$sum_i; D is generated one column at
# a time inside refresh_qF_moments(), so neither D nor resp is stored in qF.
update_qF <- function(state, a) {
  state$qF <- refresh_qF_moments(
    C = state$qZ$sum_i,
    f0 = state$f0,
    L_sum = colSums(state$L),
    pi = state$pi,
    a = a
  )
  state
}

# ---- pi-updates ----
# Use previously stored qF$resp_sumj to recover
# pi_new, which is soft counts Multinomial MLE
# However, note in implementation,
# Instead of recovering exact Multinomial MLE,
# Add Dirichlet smoothing term 
# To prevent mixture weights from getting stuck at zero
# Over future iteration
update_pi <- function(state, pseudocount = 1e-8) {
  counts <- state$qF$resp_sumj
  counts <- counts + pseudocount
  state$pi[] <- t(sweep(counts, 1L, rowSums(counts), "/"))
  state
}

# ---- update-z ----
update_qZ <- function(state, X) {
  sparse_cache <- attr(X, "bg_sparse_cache", exact = TRUE)
  if (is.null(sparse_cache) || !inherits(X, "dgCMatrix")) {
    stop("Call prepare_sparse_X(X) once before update_qZ().")
  }

  n <- nrow(X)
  p <- ncol(X)
  K <- ncol(state$L)
  log_L <- log(state$L)
  mean_log_F <- state$qF$mean_log

  # A sparse CSC matrix stores only its nonzero values and their row indices.
  # Expand the column pointers once so each stored value has matching (i, j)
  # coordinates; all qZ calculations below therefore have length nnzero(X),
  # rather than n * p.
  row_index <- sparse_cache$row_index
  column_index <- sparse_cache$column_index
  factor_score <- function(k) {
    log_L[row_index, k] + mean_log_F[column_index, k]
  }

  # Find max_k s_ijk over factors for every nonzero X_ij. This is the first
  # pass of a stable log-sum-exp and uses only nnzero(X)-length vectors.
  max_score <- factor_score(1L)

  if (K > 1L) {
    for (k in 2:K) {
      max_score <- pmax(max_score, factor_score(k))
    }
  }

  # Complete log-sum-exp in a second pass. Subtracting max_score keeps every
  # exponential at most one and prevents numerical overflow.
  weight_sum <- numeric(length(X@x))
  for (k in seq_len(K)) {
    weight_sum <- weight_sum + exp(factor_score(k) - max_score)
  }
  log_normalizer <- max_score + log(weight_sum)
  rm(max_score, weight_sum)

  # Only the summaries needed by the qF and L updates are retained. Reuse X's
  # sparse structure to aggregate one factor at a time without storing phi or
  # E[Z].
  sum_i <- matrix(0, p, K)
  sum_j <- matrix(0, n, K)
  mean_Z <- X

  for (k in seq_len(K)) {
    # log(phi_ijk) = s_ijk - log(sum_h exp(s_ijh)), evaluated only where
    # X_ij is nonzero. Consequently E[Z_ijk] = X_ij * phi_ijk is also sparse.
    log_phi <- factor_score(k) - log_normalizer
    mean_Z@x <- X@x * exp(log_phi)

    # Sufficient summaries for the qF and L updates.
    sum_i[, k] <- as.numeric(Matrix::colSums(mean_Z))
    sum_j[, k] <- as.numeric(Matrix::rowSums(mean_Z))
  }

  # Cache -sum_ijk E[Z_ijk] log(phi_ijk) for the ELBO. Since
  # log(phi_ijk) = score_ijk - log_normalizer_ij and sum_k E[Z_ijk] = X_ij,
  # the nnzero(X)-length product is needed only once, rather than once per k.
  allocation_entropy <- sum(X@x * log_normalizer)
  for (k in seq_len(K)) {
    allocation_entropy <- allocation_entropy -
      sum(sum_j[, k] * log_L[, k]) -
      sum(sum_i[, k] * mean_log_F[, k])
  }

  state$qZ <- list(
    sum_i = sum_i,
    sum_j = sum_j,
    allocation_entropy = allocation_entropy
  )
  state
}


# ---- update-L ----
# In contrast to theory, in implementation, I prevent zero L

update_L <- function(state, min_loading = 1e-12) {
  numerator <- state$qZ$sum_j
  denominator <- drop(
    crossprod(state$f0, state$qF$mean)
  )

  # Update one factor column at a time to avoid allocating full n-by-K
  # intermediate matrices for both the division and pmax operations.
  for (k in seq_along(denominator)) {
    # The ratio is the unconstrained coordinate-wise MLE for L[, k].
    # The floor prevents exact zeros so log(L) remains finite in update_qZ.
    state$L[, k] <- pmax(
      numerator[, k] / denominator[k],
      min_loading
    )
  }
  state
}

# ---- update-f0 ----
# y is calculated once, before CAVI loop
update_f0 <- function(state, y) {
  expected_rate <- drop(
    state$qF$mean %*% colSums(state$L)
  )

  state$f0[] <- y / expected_rate
  state
}


# ---- L-scaling ----
# L scaling
normalize_loading_scale <- function(state, target_mean_row_sum = 1) {
  current_scale <- mean(rowSums(state$L))
  scale_factor <- current_scale / target_mean_row_sum

  state$L <- state$L / scale_factor
  state$f0 <- state$f0 * scale_factor

  state
}

# ---- elbo-function ----
calculate_elbo <- function(state, X, a) {
  n <- nrow(X)
  p <- ncol(X)
  K <- ncol(state$L)
  M <- length(a)

  stopifnot(
    all(dim(state$L) == c(n, K)),
    length(state$f0) == p,
    all(dim(state$pi) == c(M, K)),
    all(dim(state$qF$mean) == c(p, K)),
    all(dim(state$qF$mean_log) == c(p, K)),
    all(dim(state$qF$resp_sumj) == c(K, M)),
    all(dim(state$qZ$sum_i) == c(p, K)),
    all(dim(state$qZ$sum_j) == c(n, K)),
    length(state$qF$mixture_base) == 1L,
    length(state$qZ$allocation_entropy) == 1L
  )

  # Component no. 1 of poisson_term: Expected allocated-count log rates.
  # qZ$sum_j[i, k] = sum_j E[Z_ijk] and
  # qZ$sum_i[j, k] = sum_i E[Z_ijk]. These two summaries let us evaluate
  # sum_ijk E[Z_ijk] * E[log(lambda_ijk)] without reconstructing E[Z].
  log_L <- log(state$L)
  log_f0 <- log(state$f0)
  allocated_log_rate <- 0

  for (k in seq_len(K)) {
    document_counts <- state$qZ$sum_j[, k]
    feature_counts <- state$qZ$sum_i[, k]
    positive_documents <- document_counts > 0
    positive_features <- feature_counts > 0

    # Restrict multiplication by log-rates to positive expected counts. This
    # defines the limiting value 0 * log(0) as zero when update_f0() assigns
    # f0_j = 0 to a feature whose observed column total is zero.
    allocated_log_rate <- allocated_log_rate +
      sum(
        document_counts[positive_documents] *
          log_L[positive_documents, k]
      ) +
      sum(
        feature_counts[positive_features] *
          (
            log_f0[positive_features] +
              state$qF$mean_log[positive_features, k]
          )
      )
  }

  # Component no. 2 of poisson_term: Expected total Poisson rate.
  # sum_ijk L_ik * f0_j * E[F_jk] factorizes into a product of two
  # factor-specific sums, so no n x p rate matrix is needed.
  expected_total_rate <- sum(
    colSums(state$L) *
      drop(crossprod(state$f0, state$qF$mean))
  )

  # Component no. 3 of poisson_term
  # allocation_entropy is -sum_ijk E[Z_ijk] log(phi_ijk), cached by
  # update_qZ() while log(phi) is available. As in the previous implementation,
  # the data-only constant -sum_ij lgamma(X_ij + 1) is omitted.
  # Put poisson_term together
  poisson_term <-
    allocated_log_rate -
    expected_total_rate +
    state$qZ$allocation_entropy

  # Component no. 1 of mixture_term
  # qF$mixture_base contains the conditional-Gamma contribution and the
  # categorical entropy, neither of which changes when update_pi() changes pi.
  # resp_sumj supplies the expected component counts for the remaining
  # sum_jkm r_jkm log(pi_mk) term.
  # Put mixture_term together
  component_counts <- state$qF$resp_sumj
  pi_by_factor <- t(state$pi)
  positive_counts <- component_counts > 0

  if (any(pi_by_factor[positive_counts] <= 0)) {
    mixture_term <- -Inf
  } else {
    mixture_term <-
      state$qF$mixture_base +
      sum(
        component_counts[positive_counts] *
          log(pi_by_factor[positive_counts])
      )
  }

  # Finally, return the scalar ELBO, up to the omitted data-only constant.
  poisson_term + mixture_term
}

# ---- initialization ----
# Main initialization function
# Initialize model parameters; qZ is synchronized once after any overrides.
initialize_state <- function(
    X,
    K,
    a,
    L_init = c("gamma", "deviance_kmeans", "fasttopics"),
    seed = 2L,
    kmeans_args = list(),
    fasttopics_args = list()
) {
  X <- prepare_sparse_X(X)
  L_init <- match.arg(L_init)
  stopifnot(
    K >= 1L,
    length(a) >= 1L,
    all(is.finite(a)),
    all(a > 0),
    is.list(kmeans_args),
    is.list(fasttopics_args)
  )
  n <- nrow(X)
  p <- ncol(X)
  M <- length(a)

  L <- switch(
    L_init,
    gamma = {
      set.seed(seed)
      matrix(rgamma(n * K, shape = 1, rate = 1), n, K)
    },
    deviance_kmeans = {
      kmeans_args$X <- X
      kmeans_args$K <- K
      if (is.null(kmeans_args$kmeans_seed)) {
        kmeans_args$kmeans_seed <- seed
      }
      do.call(initialize_deviance_kmeans, kmeans_args)
    },
    fasttopics = {
      fasttopics_args$X <- X
      fasttopics_args$K <- K
      if (is.null(fasttopics_args$seed)) {
        fasttopics_args$seed <- seed
      }
      do.call(initialize_fasttopics, fasttopics_args)
    }
  )

  pi <- matrix(1 / M, M, K)
  list(
    L = L,
    f0 = rep(1, p),
    pi = pi,
    qF = initialize_qF(pi, a, p)
  )
}

# Initialize qF at its Gamma-mixture prior. This is done once, before CAVI.
initialize_qF <- function(pi, a, p) {
  K <- ncol(pi)
  mean_log_by_factor <- drop(
    crossprod(pi, digamma(a) - log(a))
  )
  positive_pi <- pi > 0

  list(
    mean = matrix(1, p, K),
    mean_log = matrix(
      rep(mean_log_by_factor, each = p),
      p,
      K
    ),
    # sum_j r_{jkm} = p \pi_{mk}
    resp_sumj = p * t(pi),

    mixture_base = -p * sum(
      pi[positive_pi] * log(pi[positive_pi])
    )
  )
}


# ---- initialize_kmeans ----
# Compute signed Poisson-deviance residuals for one feature block.
poisson_deviance_residual_block <- function(
    X,
    columns,
    row_totals,
    column_totals,
    grand_total
) {
  observed <- as.matrix(X[, columns, drop = FALSE])
  storage.mode(observed) <- "double"
  expected <- tcrossprod(
    row_totals / grand_total,
    column_totals[columns]
  )

  # Half the Poisson deviance equals mu when x = 0. Evaluate x log(x/mu)
  # only where x is positive, avoiding log(0).
  deviance_half <- expected - observed
  positive <- observed > 0
  if (any(positive)) {
    x <- observed[positive]
    mu <- pmax(expected[positive], .Machine$double.xmin)
    deviance_half[positive] <- x * log(x / mu) - (x - mu)
  }

  residual <- sign(observed - expected) *
    sqrt(pmax(2 * deviance_half, 0))
  if (any(!is.finite(residual))) {
    stop("Non-finite Poisson-deviance residuals were produced.")
  }
  residual
}

# Score every feature by its total squared deviance residual, in blocks.
score_poisson_deviance_features <- function(
    X,
    block_size,
    row_totals,
    column_totals,
    grand_total
) {
  p <- ncol(X)
  score <- numeric(p)
  for (block_start in seq.int(1L, p, by = block_size)) {
    block_end <- min(p, block_start + block_size - 1L)
    columns <- seq.int(block_start, block_end)
    residual <- poisson_deviance_residual_block(
      X,
      columns,
      row_totals,
      column_totals,
      grand_total
    )
    score[columns] <- colSums(residual * residual)
  }
  score
}

# Select deviant features, cluster nonzero documents, and return initial L.
initialize_deviance_kmeans <- function(
    X,
    K,
    nfeatures = 1000L,
    block_memory_mb = 256,
    minimum_document_frequency = 5L,
    maximum_document_frequency_fraction = 0.95,
    kmeans_nstart = 25L,
    kmeans_seed = 2L,
    loading_epsilon = 1e-4
) {
  X <- prepare_sparse_X(X)
  stopifnot(
    K >= 2L,
    nfeatures >= 1L,
    is.finite(block_memory_mb),
    block_memory_mb > 0,
    minimum_document_frequency >= 0L,
    is.finite(maximum_document_frequency_fraction),
    maximum_document_frequency_fraction > 0,
    maximum_document_frequency_fraction <= 1,
    kmeans_nstart >= 1L,
    is.finite(loading_epsilon),
    loading_epsilon > 0,
    loading_epsilon < 1
  )

  n <- nrow(X)
  p <- ncol(X)
  cache <- attr(X, "bg_sparse_cache", exact = TRUE)
  grand_total <- sum(cache$row_totals)
  if (grand_total <= 0) {
    stop("X has zero grand total; deviance initialization is undefined.")
  }

  # The residual calculation holds about six dense n-by-block matrices.
  block_size <- as.integer(max(
    1,
    min(p, floor(block_memory_mb * 1e6 / (8 * 6 * n)))
  ))
  score <- score_poisson_deviance_features(
    X,
    block_size,
    cache$row_totals,
    cache$column_totals,
    grand_total
  )

  eligible_feature <-
    cache$column_totals > 0 &
    cache$document_frequency >= minimum_document_frequency &
    cache$document_frequency <=
      maximum_document_frequency_fraction * n
  eligible <- which(eligible_feature)
  if (!length(eligible)) {
    stop(
      "No features pass the nonzero-total and document-frequency filters."
    )
  }

  ranked <- eligible[
    order(-score[eligible], eligible, method = "radix")
  ]
  selected <- head(ranked, min(as.integer(nfeatures), length(ranked)))
  rm(score)

  residual <- matrix(NA_real_, n, length(selected))
  for (block_start in seq.int(1L, length(selected), by = block_size)) {
    block_end <- min(length(selected), block_start + block_size - 1L)
    positions <- seq.int(block_start, block_end)
    residual[, positions] <-
      poisson_deviance_residual_block(
        X,
        selected[positions],
        cache$row_totals,
        cache$column_totals,
        grand_total
      )
  }

  nonzero_documents <- which(cache$row_totals > 0)
  if (length(nonzero_documents) < K) {
    stop("Fewer than K nonzero-total documents are available for k-means.")
  }

  set.seed(kmeans_seed)
  cluster <- stats::kmeans(
    residual[nonzero_documents, , drop = FALSE],
    centers = K,
    nstart = kmeans_nstart,
    iter.max = 100L
  )$cluster

  # Give each clustered document one dominant factor. All-zero documents are
  # excluded from k-means and receive neutral loadings.
  L <- matrix(loading_epsilon, n, K)
  L[cbind(nonzero_documents, cluster)] <- 1
  zero_documents <- which(cache$row_totals == 0)
  L[zero_documents, ] <- 1 / K

  stopifnot(
    all(is.finite(L)),
    all(L > 0)
  )
  L
}


# ---- initialize-fasttopics ----
# Fit Poisson NMF and return a positive, column-scaled loading matrix.
initialize_fasttopics <- function(
    X,
    K,
    numiter = 200L,
    seed = 2L,
    minimum_loading = 1e-12
) {
  if (!requireNamespace("fastTopics", quietly = TRUE)) {
    stop("The fastTopics package is required for this initialization.")
  }
  stopifnot(
    K >= 1L,
    numiter >= 1L,
    length(minimum_loading) == 1L,
    is.finite(minimum_loading),
    minimum_loading > 0
  )

  X <- prepare_sparse_X(X)
  set.seed(seed)
  L <- fastTopics::fit_poisson_nmf(
    X,
    K,
    numiter = numiter,
    verbose = "none"
  )$L

  # NMF column scales are arbitrary. Match the unit-mean qF initialization
  # while retaining the relative document loadings within each factor.
  L <- pmax(L, minimum_loading)
  L <- sweep(L, 2L, colMeans(L), "/")
  stopifnot(
    all(dim(L) == c(nrow(X), K)),
    all(is.finite(L)),
    all(L > 0)
  )
  L
}

prepare_sparse_X <- function(X) {
  cached <- attr(X, "bg_sparse_cache", exact = TRUE)
  if (!is.null(cached)) {
    return(X)
  }

  if (length(dim(X)) != 2L || nrow(X) < 1L || ncol(X) < 1L ||
      (!is.matrix(X) && !inherits(X, "sparseMatrix"))) {
    stop("X must be a nonempty matrix or Matrix sparse matrix.")
  }
  if (!requireNamespace("Matrix", quietly = TRUE)) {
    stop("The Matrix package is required for sparse input.")
  }
  if (!inherits(X, "sparseMatrix")) {
    X <- Matrix::Matrix(X, sparse = TRUE)
  }
  if (!inherits(X, "dgCMatrix")) {
    X <- methods::as(X, "dgCMatrix")
  }
  X <- Matrix::drop0(X)
  if (any(!is.finite(X@x)) || any(X@x < 0)) {
    stop("X must contain finite, nonnegative counts.")
  }

  # Cache quantities determined solely by X and its fixed sparsity pattern.
  # update_qZ reuses the coordinates, while initialization and the f0 update
  # reuse the marginal counts without rescanning X.
  attr(X, "bg_sparse_cache") <- list(
    row_index = X@i + 1L,
    column_index = rep.int(seq_len(ncol(X)), diff(X@p)),
    row_totals = as.numeric(Matrix::rowSums(X)),
    column_totals = as.numeric(Matrix::colSums(X)),
    document_frequency = diff(X@p)
  )
  X
}

# ---- ebpmf-bg-function ----
run_ebpmf_bg_cavi <- function(
    state,
    X,
    a,
    max_niter = 500L,
    elbo_every = 10L,
    fit_elbo_tolerance = 1e-6,
    fit_elbo_patience = 3L,
    estimate_pi = TRUE,
    estimate_f0 = TRUE,
    early_stop = TRUE
) {
  X <- prepare_sparse_X(X)
  stopifnot(
    max_niter >= 1L,
    elbo_every >= 1L,
    fit_elbo_tolerance >= 0,
    fit_elbo_patience >= 1L,
    isTRUE(estimate_pi) || identical(estimate_pi, FALSE), # Is one logical value?
    isTRUE(estimate_f0) || identical(estimate_f0, FALSE),
    isTRUE(early_stop) || identical(early_stop, FALSE)
  )
  # Compute once and store for f0 update
  y <- attr(X, "bg_sparse_cache", exact = TRUE)$column_totals # y_j = \sum_i X_{ij}

  # Compute qZ once after initialization and any oracle overrides.
  state <- update_qZ(state, X)
  previous_elbo <- calculate_elbo(state, X, a)
  if (!is.finite(previous_elbo)) {
    stop("The initial EBPMF-BG ELBO is not finite.")
  }

  # Preallocate traces. pi_trace is retained because downstream plots use the
  # complete mixture-weight path; ELBO is stored only at checkpoints.
  n_checkpoints <- max_niter %/% elbo_every + 1L
  elbo_trace <- data.frame(
    iteration = integer(n_checkpoints),
    elbo = rep(NA_real_, n_checkpoints),
    relative_change = rep(NA_real_, n_checkpoints)
  )
  elbo_trace$elbo[1L] <- previous_elbo

  pi_trace <- array(
    NA_real_,
    dim = c(max_niter + 1L, length(a), ncol(state$L)),
    dimnames = list(
      iteration = 0:max_niter,
      mixture = paste0("a=", a),
      estimated_factor = paste0("column", seq_len(ncol(state$L)))
    )
  )
  pi_trace[1L, , ] <- state$pi

  checkpoint <- 1L
  stable_checkpoints <- 0L
  converged <- FALSE

  for (iter in seq_len(max_niter)) {
    # One coordinate-ascent sweep: F/pi, allocations, loadings, then f0.
    state <- update_qF(state, a)
    if (estimate_pi) state <- update_pi(state)
    state <- update_qZ(state, X)
    state <- update_L(state)
    if (estimate_f0) {
      state <- update_f0(state, y)
      state <- normalize_loading_scale(state)
    }
    pi_trace[iter + 1L, , ] <- state$pi

    if (iter %% elbo_every != 0L) next

    # Check convergence from successive checkpoint ELBO values.
    current_elbo <- calculate_elbo(state, X, a)
    relative_change <- abs(current_elbo - previous_elbo) /
      max(1, abs(previous_elbo))
    if (!is.finite(current_elbo) || !is.finite(relative_change)) {
      stop("The EBPMF-BG ELBO became non-finite at iteration ", iter, ".")
    }

    checkpoint <- checkpoint + 1L
    elbo_trace[checkpoint, ] <- list(iter, current_elbo, relative_change)
    stable_checkpoints <- if (relative_change <= fit_elbo_tolerance) {
      stable_checkpoints + 1L
    } else {
      0L
    }
    converged <- early_stop && stable_checkpoints >= fit_elbo_patience
    previous_elbo <- current_elbo
    if (converged) break
  }

  completed_niter <- iter
  elbo_trace <- elbo_trace[seq_len(checkpoint), , drop = FALSE]
  pi_trace <- pi_trace[seq_len(completed_niter + 1L), , , drop = FALSE]

  list(
    state = state,
    elbo_trace = elbo_trace,
    pi_trace = pi_trace,
    completed_niter = completed_niter,
    converged = converged
  )
}

# ---- simulate ----
# Simulate X and the generating L, F, f0, and pi.
simulate_background_model <- function(
    n,
    p,
    K,
    a,
    pi,
    seed = 1L,
    loading_mode = c("single", "primary_secondary"),
    primary_weight = 0.7,
    epsilon = 1e-4
) {
  loading_mode <- match.arg(loading_mode)
  M <- length(a)
  stopifnot(
    n >= K,
    p >= 1L,
    K >= 1L,
    all(is.finite(a)),
    all(a > 0),
    is.matrix(pi),
    all(dim(pi) == c(M, K)),
    all(is.finite(pi)),
    all(pi >= 0),
    all(abs(colSums(pi) - 1) < 1e-10),
    length(epsilon) == 1L,
    is.finite(epsilon),
    epsilon > 0,
    K * epsilon < 1
  )
  if (loading_mode == "primary_secondary") {
    stopifnot(
      K >= 2L,
      length(primary_weight) == 1L,
      is.finite(primary_weight),
      primary_weight > 0,
      primary_weight < 1
    )
  }

  set.seed(seed)
  # Draw each feature's Gamma-mixture component and factor value.
  F <- matrix(0, p, K)
  for (k in seq_len(K)) {
    component <- sample.int(M, p, replace = TRUE, prob = pi[, k])
    F[, k] <- rgamma(p, shape = a[component], rate = a[component])
  }

  # Assign balanced primary groups.
  group_size <- rep(n %/% K, K)
  group_size[seq_len(n %% K)] <- group_size[seq_len(n %% K)] + 1L
  primary <- rep(seq_len(K), group_size)

  L <- matrix(epsilon, n, K)
  row <- seq_len(n)
  if (loading_mode == "single") {
    L[cbind(row, primary)] <- 1 - (K - 1L) * epsilon
  } else {
    # Select a secondary factor uniformly, excluding the primary factor.
    secondary <- (
      primary - 1L + sample.int(K - 1L, n, replace = TRUE)
    ) %% K + 1L

    # Split the mass left after assigning epsilon to inactive factors.
    active_mass <- 1 - (K - 2L) * epsilon
    L[cbind(row, primary)] <- primary_weight * active_mass
    L[cbind(row, secondary)] <- (1 - primary_weight) * active_mass
  }

  f0 <- exp(rnorm(p, sd = 0.4)) # Increase sd for stronger heterogeneity
  f0 <- f0 / mean(f0) # Now f0 represents relative feature-specific background intensity

  # A sum of independent Poisson variables is Poisson with the summed rate,
  # so neither component-specific rates nor an n x p x K latent Z are needed.
  X <- tcrossprod(L, F * f0)
  X[] <- rpois(length(X), X)
  X <- prepare_sparse_X(X)

  list(X = X, L = L, F = F, f0 = f0, pi = pi)
}

